[dependencies]
env_logger = {default-features = false, features = [
  "auto-color",
  "humantime"
], version = "=0.11.2"}
gtk = "=0.18.1"
gtk-layer-shell = "=0.8.0"
log = "=0.4.20"
nameof = "=1.2.2"
serde_json = {default-features = false, features = [
  "std"
], version = "=1.0.113"}

[package]
edition = "2021"
license = "MIT"
name = "vosd"
version = "0.1.0"

[profile.release]
codegen-units = 1
lto = true
strip = true
